[project]
name = "webhm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yrii Chernyshov", email = "c300@list.ru" }
]
requires-python = ">=3.14"
dependencies = [
    "coloredstrings>=3.3.0",
]

[project.scripts]
webhm = "webhm:main" 

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
 